- name: Integrating Ansible with Jenkins
  hosts: all
  become: yes
  tasks: 
    - name: Installing apache2
      apt:
        name: apache2
        state: present

    - name: Starting apache2
      service: 
        name: apache2
        state: started

    - name: Copy index.html to web root
      copy:
        src: index.html
        dest: /var/www/html/
